# Site settings
title: Gertjan Assies Dev
description: 'Ramblings of a chaotic mind'
url: 'https://blog.gertjanassies.dev'
baseurl: ''
google_analytics: 'UA-136450675-1'
disqus_shortname: 'gertjan-assies-dev'
show_drafts: true

author:
  name: 'Gertjan Assies'
  email: gertjan.assies@gmail.com
  twitter_username: major7
  github_username:  gertjana

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 6
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

webrick:
  headers:
    Strict-Transport-Security: "Strict-Transport-Security: max-age=31536000; includeSubDomains" 
    Content-Security-Policy: "script-src 'self'"
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection:  "X-XSS-Protection: 1; mode=block"
    X-Content-Type-Options:  "nosniff"
    Referrer-Policy: "strict-origin"
    Feature-Policy:  "camera 'none'; microphone 'none'; sync-xhr 'none'; geolocation 'none';"
